services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    stdin_open: true
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    env_file:
      - path: ./.env.local
        required: true
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_USERNAME=Admin
      - DJANGO_SUPERUSER_PASSWORD=Password
      - DJANGO_SUPERUSER_FIRST_NAME=tom
      - DJANGO_SUPERUSER_LAST_NAME=astro
      - DJANGO_SUPERUSER_ROLE=1
      - DJANGO_SUPERUSER_INSTITUTE=NCU
      - DJANGO_SUPERUSER_USE_DEMO_TARGETS=True
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    restart: always
    volumes:
      - NCU_TOM_Local:/var/lib/postgresql/data
    env_file:
      - path: ./.env.local
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEBUG: true
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  NCU_TOM_Local:
    name: NCU_TOM_Local
