services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_SERVER_API_HOST=${NEXT_PUBLIC_SERVER_API_HOST}
        - NEXT_HOME_URL=${NEXT_HOME_URL}
    env_file:
      - path: ./.env.prod
        required: true
    stdin_open: true
    ports:
      - "3000:3000"

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: "/app/entrypoint.sh"
    env_file:
      - path: ./.env.prod
        required: true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /Users/cassiopeia/pipeline_working_dir/LOT/Calibrated_Science:/app/data:ro
    ports:
      - 8000:8000

  db:
    image: postgres:17.2
    restart: always
    volumes:
      - NCU_TOM:/var/lib/postgresql/data
    env_file:
      - path: ./.env.prod
        required: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    depends_on:
      - react
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  NCU_TOM:
    name: NCU_TOM
