# Generated by Django 4.2.6 on 2024-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
