# Generated by Django 4.2.6 on 2024-10-26 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='dec',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='ra',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['ra', 'dec'], name='target_coords'),
        ),
    ]
