# Generated by Django 5.1.3 on 2026-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
