# Generated by Django 4.2.6 on 2024-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='hashed_sed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='hashed_simbad',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='sed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='simbad',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
