# Generated by Django 4.2.6 on 2024-09-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='Tag',
        ),
    ]
