# Generated by Django 4.2.6 on 2024-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='use_demo_targets',
            field=models.BooleanField(default=True),
        ),
    ]
