# Generated by Django 4.2.6 on 2024-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_users_use_demo_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='title',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Faculty'), (3, 'User')]),
        ),
    ]
