# Generated by Django 4.2.6 on 2024-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_alter_users_is_active_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
