# Generated by Django 5.1.3 on 2026-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
