# Generated by Django 4.2.6 on 2024-10-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpers', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('observatory', models.IntegerField(choices=[(1, 'Lulin')], default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Too')], default=3)),
                ('status', models.IntegerField(choices=[(1, 'Prep'), (2, 'Pending'), (3, 'In Progress'), (4, 'Done'), (5, 'Expired'), (6, 'Denied'), (7, 'Postponed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('comments', models.ManyToManyField(related_name='observations', to='helpers.comments')),
                ('tags', models.ManyToManyField(related_name='observations', to='helpers.tags')),
                ('targets', models.ManyToManyField(to='targets.target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Observation',
            },
        ),
        migrations.CreateModel(
            name='LulinRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Too')], default=3)),
                ('binning', models.IntegerField(default=1)),
                ('frames', models.IntegerField(default=1)),
                ('exposure_time', models.IntegerField(default=10)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Fail'), (3, 'Pending'), (4, 'Partial Success'), (5, 'Rescheduled')], default=3, verbose_name='Status')),
                ('filter', models.IntegerField(choices=[(1, 'u'), (2, 'g'), (3, 'r'), (4, 'i'), (5, 'z')], default=1, null=True, verbose_name='Filter')),
                ('instrument', models.IntegerField(choices=[(1, 'LOT'), (2, 'SLT'), (3, 'TRIPOL')], default=1, null=True, verbose_name='Instruments')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observation')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.target')),
            ],
            options={
                'db_table': 'LulinRun',
            },
        ),
    ]
