# Generated by Django 5.1.3 on 2024-12-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LulinRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Too')], default=3)),
                ('binning', models.IntegerField(default=1)),
                ('frames', models.IntegerField(default=1)),
                ('exposure_time', models.IntegerField(default=10)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Fail'), (3, 'Pending'), (4, 'Partial Success'), (5, 'Rescheduled')], default=3, verbose_name='Status')),
                ('filter', models.IntegerField(choices=[(1, 'u'), (2, 'g'), (3, 'r'), (4, 'i'), (5, 'z')], default=1, null=True, verbose_name='Filter')),
                ('instrument', models.IntegerField(choices=[(1, 'LOT'), (2, 'SLT'), (3, 'TRIPOL')], default=1, null=True, verbose_name='Instruments')),
            ],
            options={
                'db_table': 'LulinRun',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('observatory', models.IntegerField(choices=[(1, 'Lulin')], default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Too')], default=3)),
                ('status', models.IntegerField(choices=[(1, 'Prep'), (2, 'Pending'), (3, 'In Progress'), (4, 'Done'), (5, 'Expired'), (6, 'Denied'), (7, 'Postponed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Observation',
            },
        ),
    ]
