# Generated by Django 5.1.3 on 2024-12-23 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0002_initial'),
        ('observations', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lulinrun',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.target'),
        ),
        migrations.AddField(
            model_name='observation',
            name='comments',
            field=models.ManyToManyField(related_name='observations', to='helpers.comments'),
        ),
        migrations.AddField(
            model_name='observation',
            name='tags',
            field=models.ManyToManyField(related_name='observations', to='helpers.tags'),
        ),
        migrations.AddField(
            model_name='observation',
            name='targets',
            field=models.ManyToManyField(to='targets.target'),
        ),
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lulinrun',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observation'),
        ),
    ]
