# Generated by Django 4.2.6 on 2024-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
