# Generated by Django 4.2.6 on 2024-11-06 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='targets',
            field=models.ManyToManyField(to='targets.target'),
        ),
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lulinrun',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observation'),
        ),
        migrations.AddField(
            model_name='lulinrun',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.target'),
        ),
    ]
