# Generated by Django 4.2.6 on 2024-07-11 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0002_observation_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulin',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Too')], default=3),
        ),
        migrations.AlterField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
