# Generated by Django 4.2.6 on 2024-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_lulin_priority_alter_observation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
