# Generated by Django 4.2.6 on 2024-10-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproducts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lulindataproduct',
            name='instrument_mag',
        ),
        migrations.RemoveField(
            model_name='lulindataproduct',
            name='photometric_band',
        ),
    ]
