# Generated by Django 4.2.6 on 2024-10-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_alter_target_dec_alter_target_ra_and_more'),
        ('dataproducts', '0005_etllogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulindataproduct',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lulin_data_products', to='targets.target'),
        ),
    ]
